version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "your-stack-name"
s3_bucket = "your-sam-deployment-bucket"
s3_prefix = "your-prefix"
region = "sa-east-1" # esta región tiene que coincidir siempre con la región en la que estamos trabajando en AWS
confirm_changeset = true
capabilities = "CAPABILITY_IAM"